### ISSUE TITLE
Server crashed 10 times in the last minute.

### ISSUE THREAD

**Issue by baykus871** [Pure-D/code-d#340]
I started my vscode and code-d doesn't started properly.
It says that a problem occured at server connection:

```
[Info  - 18:42:46] Connection to server got closed. Server will restart.
[Info  - 18:42:46] Connection to server got closed. Server will restart.
[Info  - 18:42:47] Connection to server got closed. Server will restart.
[Info  - 18:42:47] Connection to server got closed. Server will restart.
[Info  - 18:42:48] Connection to server got closed. Server will restart.
[Info  - 18:42:48] Connection to server got closed. Server will restart.
[Info  - 18:42:49] Connection to server got closed. Server will restart.
[Info  - 18:42:49] Connection to server got closed. Server will restart.
[Info  - 18:42:50] Connection to server got closed. Server will restart.
Server crashed 10 times in the last minute. The server will not be restarted.
[Error - 18:42:50] Connection to server got closed. Server will not be restarted.
```

--> Then **nothing** happens. So i can't write any d file with using extension.

**Comment by WebFreak001** [comment]
does this happen with a certain project?

Try if this is already fixed in nightly by changing your user setting "Served Release Channel" to "nightly" and then reloading VSCode (if you are on windows, make sure you only have a single vscode window open)

**Comment by baykus871** [comment]
I did what you said. I just be sure for one vscode window open and i switched my setting to "nightly". 👍 
Now my terminal was stucked here:

```
Installing into C:\Users\burak\AppData\Roaming\code-d\bin
| (It wants that i wait But I will not do that. ... heh)
```

**Comment by baykus871** [comment]
If you want to truth then i say:
  * My Avast antivirus deleted **dcd-server.exe** and deleted other files in `./code-d/bin`. After that, the extension => *blow up*!.
Has code-d extension **virus**?

**Comment by WebFreak001** [comment]
duplicate of Pure-D/serve-d#107 then

**Comment by baykus871** [comment]
I can handle with antivirus. However this problem still lives. My shell stucked, extension too. 😄
How can i fix this problem?

**Comment by baykus871** [comment]
If you are saying there is no solution for this then,
I must search other extensions in vscode or may be other things which useful.
Otherwise my projects all be gone to void.
Because the extension so good and i can write codes perfectly.

**Comment by WebFreak001** [comment]
Please open a simple hello world project, add "serve-d.trace.server": "verbose" to your user settings (edit as JSON, ignore that it's unrecognized) and reload the window once more.

Then go to the output tab in the bottom panel and select "code-d / serve-d output", then copy the output and upload it somewhere such as https://gist.github.com and post it here. The output contains all open code and paths, so make sure you do this on a smallest possible project.

**Comment by baykus871** [comment]
**Result** is:
 https://gist.github.com/baykus871/d2e62ed292684d81a8f20594bba65d3e
